dropout: 0.0
embed_dim: 128
hidden_dim: 128
input_chord_pitch_type: &id001 !!python/object/apply:harmonic_inference.data.data_types.PitchType
- 0
input_key_pitch_type: *id001
learning_rate: 0.001
lstm_hidden_dim: 128
lstm_layers: 1
reduction: null
use_inversions: true
