dropout: 0.0
embed_dim: 256
hidden_dim: 256
input_type: !!python/object/apply:harmonic_inference.data.data_types.PieceType
- 0
learning_rate: 0.001
lstm_hidden_dim: 128
lstm_layers: 1
pitch_type: !!python/object/apply:harmonic_inference.data.data_types.PitchType
- 0
